#! /bin/sh
##
# this script needs to be run as the reporting user, and so needs to have its stciky bit set (chmod ug+s)
# does 2 things:
# 1) invoke a one-time startup task
# 2) start the delayed_job background worker as a daemon and let it run
# 
# do not edit -- generated by Chef -- will be overwritten
##

APP_DIR=/srv/netpop-reporting/current
APP_ENV=reporting

RAILS_ENV=$APP_ENV $APP_DIR/script/runner 'ReportServer.startup_event!'
start-stop-daemon --start --exec /usr/bin/rake jobs:work 2>&1 --chdir /srv/netpop-reporting/current --chuid reporting --make-pidfile --pidfile /srv/netpop-reporting/current/tmp/pids/netpop-reporting-dj.pid --background -- RAILS_ENV=reporting
